spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/shop_clothing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: NewStrongPass!123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO

server:
  port: 0

app:
  security:
    admin:
      username: admin
      password: admin